[2022-01-24 02:36:12,528] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: datawarehouse_etl.load_invoices scheduled__2022-01-01T00:00:00+00:00 [queued]>
[2022-01-24 02:36:12,537] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: datawarehouse_etl.load_invoices scheduled__2022-01-01T00:00:00+00:00 [queued]>
[2022-01-24 02:36:12,537] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-24 02:36:12,537] {taskinstance.py:1239} INFO - Starting attempt 3 of 3
[2022-01-24 02:36:12,537] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-24 02:36:12,548] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): load_invoices> on 2022-01-01 00:00:00+00:00
[2022-01-24 02:36:12,552] {standard_task_runner.py:52} INFO - Started process 2584 to run task
[2022-01-24 02:36:12,555] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'datawarehouse_etl', 'load_invoices', 'scheduled__2022-01-01T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/datawarehouse_***.py', '--cfg-path', '/tmp/tmpkmfpjpxj', '--error-file', '/tmp/tmpofcdsbn8']
[2022-01-24 02:36:12,556] {standard_task_runner.py:77} INFO - Job 47: Subtask load_invoices
[2022-01-24 02:36:12,594] {logging_mixin.py:109} INFO - Running <TaskInstance: datawarehouse_etl.load_invoices scheduled__2022-01-01T00:00:00+00:00 [running]> on host cd9bb47288d1
[2022-01-24 02:36:12,632] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=datawarehouse_etl
AIRFLOW_CTX_TASK_ID=load_invoices
AIRFLOW_CTX_EXECUTION_DATE=2022-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-01T00:00:00+00:00
[2022-01-24 02:36:12,633] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 02:36:12,633] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 02:36:12,633] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 02:36:12,633] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 02:36:12,633] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 02:36:12,633] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 02:36:12,634] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 02:36:12,634] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 02:36:12,634] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 02:36:12,634] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 02:36:12,634] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 02:36:12,634] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 02:36:12,634] {logging_mixin.py:109} INFO - {'conf': <***.configuration.AirflowConfigParser object at 0x7f1e4dfc6a10>, 'dag': <DAG: datawarehouse_etl>, 'dag_run': <DagRun datawarehouse_etl @ 2022-01-01 00:00:00+00:00: scheduled__2022-01-01T00:00:00+00:00, externally triggered: False>, 'data_interval_end': DateTime(2022, 1, 2, 0, 0, 0, tzinfo=Timezone('UTC')), 'data_interval_start': DateTime(2022, 1, 1, 0, 0, 0, tzinfo=Timezone('UTC')), 'ds': '2022-01-01', 'ds_nodash': '20220101', 'execution_date': DateTime(2022, 1, 1, 0, 0, 0, tzinfo=Timezone('UTC')), 'inlets': [], 'logical_date': DateTime(2022, 1, 1, 0, 0, 0, tzinfo=Timezone('UTC')), 'macros': <module '***.macros' from '/home/***/.local/lib/python3.7/site-packages/***/macros/__init__.py'>, 'next_ds': '2022-01-02', 'next_ds_nodash': '20220102', 'next_execution_date': DateTime(2022, 1, 2, 0, 0, 0, tzinfo=Timezone('UTC')), 'outlets': [], 'params': {}, 'prev_data_interval_start_success': None, 'prev_data_interval_end_success': None, 'prev_ds': '2021-12-31', 'prev_ds_nodash': '20211231', 'prev_execution_date': datetime.datetime(2021, 12, 31, 0, 0, tzinfo=Timezone('UTC')), 'prev_execution_date_success': None, 'prev_start_date_success': None, 'run_id': 'scheduled__2022-01-01T00:00:00+00:00', 'task': <Task(PythonOperator): load_invoices>, 'task_instance': <TaskInstance: datawarehouse_etl.load_invoices scheduled__2022-01-01T00:00:00+00:00 [running]>, 'task_instance_key_str': 'datawarehouse_etl__load_invoices__20220101', 'test_mode': False, 'ti': <TaskInstance: datawarehouse_etl.load_invoices scheduled__2022-01-01T00:00:00+00:00 [running]>, 'tomorrow_ds': '2022-01-02', 'tomorrow_ds_nodash': '20220102', 'ts': '2022-01-01T00:00:00+00:00', 'ts_nodash': '20220101T000000', 'ts_nodash_with_tz': '20220101T000000+0000', 'var': {'json': None, 'value': None}, 'conn': None, 'yesterday_ds': '2021-12-31', 'yesterday_ds_nodash': '20211231', 'key': 'value', 'ts_var': '2022-01-01T00:00:00+00:00', 'tsnodash_var': '20220101T000000', 'templates_dict': None}
[2022-01-24 02:36:12,635] {logging_mixin.py:109} INFO - ts:  2022-01-01 00:00:00+00:00
[2022-01-24 02:36:12,635] {logging_mixin.py:109} INFO - <class 'pandas._libs.tslibs.timestamps.Timestamp'>
[2022-01-24 02:36:12,635] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/datawarehouse_airflow.py", line 46, in load_invoices
    print(ts.year())
TypeError: 'int' object is not callable
[2022-01-24 02:36:12,645] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=datawarehouse_etl, task_id=load_invoices, execution_date=20220101T000000, start_date=20220124T023612, end_date=20220124T023612
[2022-01-24 02:36:12,655] {standard_task_runner.py:92} ERROR - Failed to execute job 47 for task load_invoices
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/datawarehouse_airflow.py", line 46, in load_invoices
    print(ts.year())
TypeError: 'int' object is not callable
[2022-01-24 02:36:12,687] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-24 02:36:12,737] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
