[2022-01-24 02:18:18,444] {taskinstance.py:1026} INFO - Dependencies not met for <TaskInstance: datawarehouse_etl.load_invoices scheduled__2022-01-12T00:00:00+00:00 [queued]>, dependency 'Execution Date' FAILED: The execution date is 2022-01-12T00:00:00+00:00 but this is after the task's end date 2022-01-05T06:00:00+00:00.
[2022-01-24 02:18:18,450] {local_task_job.py:99} INFO - Task is not able to be run
[2022-01-24 02:20:07,802] {taskinstance.py:1026} INFO - Dependencies not met for <TaskInstance: datawarehouse_etl.load_invoices scheduled__2022-01-12T00:00:00+00:00 [queued]>, dependency 'Execution Date' FAILED: The execution date is 2022-01-12T00:00:00+00:00 but this is after the task's end date 2022-01-05T00:00:00+00:00.
[2022-01-24 02:20:07,808] {local_task_job.py:99} INFO - Task is not able to be run
